Server:
RunMode:debug
HttpPort:8000
ReadTimeout:60
WriteTimeout:60

App:
DefaultPageSize:10
MaxPageSize:100
LogSavePath:storage/log
LogFileName:app
LogFileExt:.log

Database:
DBType:mysql
Username:goweb  #数据库帐号
Password:123qwe  #数据库密码
Host:10.0.0.207:3306
DBName:blog_service
TablePrefix:blog_
Charset:utf8
ParseTime:True
MaxIdleConns:10
MaxOpenConns:30


