Server:
RunMode:debug
HttpPort:8000
ReadTimeout:60
WriteTimeout:60

App:
DefaultPageSize:10
MaxPageSize:100
LogSavePath:storage/log
LogFileName:app
LogFileExt:.log
UploadSavePath:storage/uploads
UploadServerUrl:http://12.0.0.1:8080/static
UploadImageMaxSize:5  #MB
UploadImageAllowExt:
   - .jpg
   - .jpeg
   - .png

Email:
Host:smtp.qq.com
Port:465
UserName:xxx
Password:xxx
To:
  - xxx

JWT:
 Secret:edd
 Issuer:blog_service
 Expire:7200
 
Database:
DBType:mysql
Username:goweb  #数据库帐号
Password:123qwe  #数据库密码
Host:10.0.0.207:3306
DBName:blog_service
TablePrefix:blog_
Charset:utf8
ParseTime:True
MaxIdleConns:10
MaxOpenConns:30


